export enum EnvironmentVariables {
    PORT = 'PORT',
    MONGODB_URL = 'MONGODB_URL',
    SWAGGER_TITLE = 'SWAGGER_TITLE',
    SWAGGER_DESCRIPTION = 'SWAGGER_DESCRIPTION',
    SWAGGER_VERSION = 'SWAGGER_VERSION',
    CORS_ORIGIN = 'CORS_ORIGIN',
}
